<a href="https://colab.research.google.com/github/giulia-mascarin/machine_learning/blob/main/Lab00_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print(np.__version__)

2.0.2


Numpy provides many functions to **create** arrays


In [ ]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.84442847 0.86468485]
 [0.56219513 0.05303487]]



**Slicing:** In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing.


In [ ]:
nums = list(range(5))     # range is a built-in function that creates a list of integers
nums = np.array(nums)     # convert python list to numpy array
print(nums)               # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(nums[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"
nums[2:4] = [8, 9]        # Create a new sub-array
print(nums)
print(nums.shape)

[0 1 2 3 4]
[2 3]
[2 3 4]
[0 1]
[0 1 2 3 4]
[0 1 2 3]
[0 1 8 9 4]
(5,)



Let us see some examples of **Matrix** **multiplication**


In [ ]:
import time  # import module to calculate execution time


In [ ]:
x = np.array([1, 0.01, 0.5, 0.78])
w = np.array([1, 2, 3, -3])
b = 0.5

start_time = time.time()
y = np.dot(w, x) + b  # linear regression
end_time = time.time()
print(y)
print(y.shape)

vec_time = end_time-start_time
print("Execution time with vectorization {} seconds".format(vec_time))

0.6800000000000002
()
Execution time with vectorization 0.0001590251922607422 seconds


The same result can be obtained with a less efficient for loop.

In [ ]:
start_time = time.time()
x_n = x.shape[0]
y = 0
for i in range(x_n):
   y += w[i]*x[i] + b
end_time = time.time()

print(y)
print(y.shape)

print("Execution time without vectorization {} seconds".format(end_time-start_time))
print(vec_time/(end_time-start_time))   # print the increase in execution time
                                        # warning: for small vectors it varies a lot between runs!

2.1799999999999997
()
Execution time without vectorization 0.0002875328063964844 seconds
0.5530679933665008


The matmul function allow to multiply N-Dimensional arrays - the behaviour



In [ ]:
a = np.random.random_sample(size=(5,3))  # generate random matrix with 5 rows and 3 columns
b = np.random.random_sample(size=(3,4))  # generate random matrix with 3 rows and 4 columns

print(a)
print(b)

c = np.matmul(a,b)
print(c)
print(c.shape)     # prints the shape of the resulting matrix, e.g. (5,4)


What happens if the inner dimensions are not compatible?


In [ ]:
print(np.matmul(b, a))

Let us see another example of how a vectorized implementation is more efficient!


In [ ]:
a = np.random.random_sample((5000,))    # generate a large vector

# vectorized calculation
start_time = time.time()
exp_a = np.exp(a)
end_time = time.time()
print("Execution time with vectorization {} seconds".format(end_time-start_time))

start_time = time.time()
x_n = a.shape[0]
exp_a = np.zeros(a.shape)
for i in range(x_n):
   exp_a[i] = np.exp(a[i])
end_time = time.time()
print("Execution time without vectorization {} seconds".format(end_time-start_time))


**Exercise 1**


Given the amount of Carbs, Proteins, Fats in 100g of different foods,
knowing that carbs and proteins provides 4 calories and fats 9 calories,
calculate the % of calories from carbs, proteins and fats for each food


In [ ]:
grams = np.array([[ 27, 5.8, 41.5, 18.0 ], [ 0.7, 2.5, 8, 4 ],[ 0.2, 0.3, 1.2, 29.5 ]])
grams

array([[27. ,  5.8, 41.5, 18. ],
       [ 0.7,  2.5,  8. ,  4. ],
       [ 0.2,  0.3,  1.2, 29.5]])

In [ ]:
for i in range(grams.shape[1]):
  print(grams[:,i]/100)

[0.27  0.007 0.002]
[0.058 0.025 0.003]
[0.415 0.08  0.012]
[0.18  0.04  0.295]


**Exercise 2**

Given two 1-D arrays **x** (real values) and **y** (discreet labels), and a constant parameter *m*, implement the following formula:

$z_i = \bigg \{ \begin{matrix} \parallel x_i \parallel ^ 2 \text{  if  } y_i =1 \\ \parallel m - x_i \parallel ^ 2 \text{  if  } y_i = 0 \end{matrix}$

In [ ]:
x = np.array([0.08444168, 0.5717077,  0.86764178, 0.2427889,  0.44898618, 0.23330771,
 0.14876752, 0.41267104, 0.38951113, 0.60130308])
print(x)
y = np.array([0, 0, 1, 1, 0, 0, 0, 1, 1, 0])
print(y)


[0.08444168 0.5717077  0.86764178 0.2427889  0.44898618 0.23330771
 0.14876752 0.41267104 0.38951113 0.60130308]
[0 0 1 1 0 0 0 1 1 0]


In [ ]:
m = 5
for i in range(x.size):
  if y[i] == 1:
    print(np.linalg.norm(x[i])**2)
  else:
    print((m-x[i])**2)

24.16271359732122
19.60977269423929
0.7528022584015684
0.05894644996321
20.71172678983099
22.721355387545444
23.534456575006953
0.1702973872546816
0.15171892039387688
19.348534594017487


**Exercise 3**

Given a matrix x of size M by N, where M is the number of samples and N is the number of features, write a vectorized expression to perform min-max scaling:
𝑥′=  (𝑥  − min⁡(𝑥))/(max⁡(𝑥)−min⁡(𝑥))



In [ ]:
mat = np.random.random_sample(size=(3,5))
mat_scaled = (mat - np.min(mat))/(np.max(mat)-np.min(mat))
print(mat)
print(mat_scaled)

[[0.63029764 0.60515898 0.9121552  0.70241272 0.20073098]
 [0.43541978 0.58461187 0.45169967 0.95356083 0.72406492]
 [0.46773786 0.55084058 0.87447484 0.10619488 0.31403908]]
[[0.61850817 0.58884133 0.95113607 0.70361317 0.11156467]
 [0.38852741 0.56459313 0.40773975 1.         0.72916553]
 [0.42666687 0.52473869 0.90666843 0.         0.24528269]]


**Exercise 4**


Given a 1D array, calculate the average of each consecutive triplet


In [ ]:
x = np.array([1, 3, 5, 10, 15, 12, 23, 5, 6])

size_mean_array = x.size - 2

for i in range(size_mean_array):
  print(np.mean(x[i:i+3]))


3.0
6.0
10.0
12.333333333333334
16.666666666666668
13.333333333333334
11.333333333333334
